#!/usr/bin/env python3
"""Generate Quarto draft metadata for post kinds disabled on the homepage."""

from __future__ import annotations

import re
from pathlib import Path


POST_KINDS = ("full-research", "mini-research", "explanatory", "misc")
PROJECT_DIR = Path(__file__).resolve().parent.parent
VISIBILITY_PATH = PROJECT_DIR / "_post_visibility.yml"
DRAFTS_PATH = PROJECT_DIR / "_hidden_posts.yml"


def read_visibility() -> dict[str, bool]:
    visibility: dict[str, bool] = {}
    in_settings = False

    for line in VISIBILITY_PATH.read_text(encoding="utf-8").splitlines():
        if line.strip() == "post-kind-visibility:":
            in_settings = True
            continue
        if in_settings and line and not line.startswith((" ", "#")):
            break
        if not in_settings:
            continue

        match = re.match(r"^\s+([a-z-]+):\s*(true|false)\s*(?:#.*)?$", line)
        if match:
            visibility[match.group(1)] = match.group(2) == "true"

    missing = [kind for kind in POST_KINDS if kind not in visibility]
    unknown = sorted(set(visibility) - set(POST_KINDS))
    if missing or unknown:
        raise ValueError(
            "_post_visibility.yml must define exactly these post kinds: "
            + ", ".join(POST_KINDS)
        )

    return visibility


def read_kind(post_path: Path) -> str:
    source = post_path.read_text(encoding="utf-8")
    front_matter = re.match(r"^---\s*\n(.*?)\n---", source, re.DOTALL)
    kind_match = (
        re.search(r"^kind:\s*([a-z-]+)\s*(?:#.*)?$", front_matter.group(1), re.MULTILINE)
        if front_matter
        else None
    )
    if kind_match is None:
        raise ValueError(f"{post_path.relative_to(PROJECT_DIR)} is missing a kind field")

    kind = kind_match.group(1)
    if kind not in POST_KINDS:
        raise ValueError(f"{post_path.relative_to(PROJECT_DIR)} has unknown kind: {kind}")
    return kind


def hidden_posts(visibility: dict[str, bool]) -> list[str]:
    # No section enabled means the homepage falls back to a single
    # chronological listing of everything, so nothing is hidden. Returning
    # before the scan also keeps the default configuration independent of the
    # kind field: a post that is missing one, or carries a malformed one,
    # cannot break the published site until a section is actually turned on.
    if not any(visibility.values()):
        return []

    paths: list[str] = []
    for post_path in sorted((PROJECT_DIR / "posts").rglob("index.qmd")):
        if not visibility[read_kind(post_path)]:
            paths.append(post_path.relative_to(PROJECT_DIR).as_posix())
    return paths


def render_drafts_metadata(paths: list[str], sections_active: bool) -> str:
    # sections-active is project-level metadata, so it is merged into every
    # post document and the homepage listings can match on it. Each of the
    # four kind listings requires sections-active: "true", which is what
    # empties them when no section is enabled and leaves the chronological
    # fallback listing as the only one with items.
    #
    # This gate is what makes the fallback work at all. A listing is always
    # rendered once it is declared, and Quarto injects it after every Lua
    # filter phase, so the filter cannot delete an unwanted listing -- it can
    # only remove the surrounding heading. Emptying the listing is the part
    # the filter cannot do on its own.
    header = (
        "# Generated by scripts/update_post_visibility.py from _post_visibility.yml.\n"
        "# Do not edit this file directly.\n"
        f'sections-active: "{str(sections_active).lower()}"\n'
        "website:\n"
    )
    if not paths:
        return header + "  drafts: []\n"

    drafts = "".join(f"    - {path}\n" for path in paths)
    return header + "  drafts:\n" + drafts


def main() -> None:
    visibility = read_visibility()
    paths = hidden_posts(visibility)
    content = render_drafts_metadata(paths, any(visibility.values()))
    if not DRAFTS_PATH.exists() or DRAFTS_PATH.read_text(encoding="utf-8") != content:
        DRAFTS_PATH.write_text(content, encoding="utf-8")
    if paths:
        print("Hidden post pages: " + ", ".join(paths))


if __name__ == "__main__":
    main()
